# Generated by Django 5.0.6 on 2024-06-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='g',
        ),
    ]
