# Generated by Django 5.0.6 on 2024-06-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_videoupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoUpload',
        ),
    ]
