# Generated by Django 5.0.6 on 2024-06-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_delete_videoupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='karoakedetails',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='mp3s/'),
        ),
    ]
