# Generated by Django 5.0.6 on 2024-06-30 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_karoakedetails_mp3_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karoakedetails',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.userreg'),
        ),
    ]
