# Generated by Django 5.0.6 on 2024-06-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_alter_karoakedetails_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
