# Generated by Django 5.0.6 on 2024-06-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_userreg_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karoakedetails',
            name='userid',
        ),
    ]
