# Generated by Django 5.0.6 on 2024-06-30 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(upload_to='images/')),
                ('ordered_date', models.DateField()),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.userreg')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_pic', models.ImageField(upload_to='')),
                ('song_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.order')),
            ],
        ),
    ]
