# Generated by Django 5.0.6 on 2024-07-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0014_audiorecording'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiorecording',
            old_name='audio_file',
            new_name='background_file',
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='combined_file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='voice_file',
            field=models.FileField(default=1, upload_to='recordings/'),
            preserve_default=False,
        ),
    ]
