# Generated by Django 5.0.6 on 2024-07-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0015_rename_audio_file_audiorecording_background_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiorecording',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='audiorecording',
            old_name='voice_file',
            new_name='voice_recording',
        ),
        migrations.RemoveField(
            model_name='audiorecording',
            name='title',
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='background_file',
            field=models.FileField(upload_to='karaoke/'),
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='combined_file',
            field=models.FileField(blank=True, null=True, upload_to='combined/'),
        ),
    ]
